### ISSUE TITLE
add vertical rhythm utilities

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#144]
Every component has to deal with distances.
Most of the time those distances repeat. So we should extract an applicable pattern for it.

Further more those distances respond to the device's dimension.

# Todo

- [x] set base distance -> `10px`?
- [x] enforce single direction margin -> `margin-top`
   expect for:
   - Elements which are out of document flow, like: positioned elements, floats, etc.
   - flexed elements
- [x] containers pad
- [x] items margin

# Nice to have

- [ ] various type-specific distances -> `<h1>` to `<h6>`, `<p>`, `<ul>`/`<ol>`, ...

# Nice Reads

- [Single-direction margin declarations](https://csswizardry.com/2012/06/single-direction-margin-declarations/)
- [What You Should Know About Collapsing Margins](https://css-tricks.com/what-you-should-know-about-collapsing-margins/)
- [4 Simple Steps to Vertical Rhythm](http://typecast.com/blog/4-simple-steps-to-vertical-rhythm)
- [Why is Vertical Rhythm an Important Typography Practice?](https://zellwk.com/blog/why-vertical-rhythms/)
- [Aesthetic Sass 3: Typography and Vertical Rhythm](https://scotch.io/tutorials/aesthetic-sass-3-typography-and-vertical-rhythm)

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
