### ISSUE TITLE
[Parent] Refactor materials module

### ISSUE THREAD

**Issue by MKaHead** [axa-ch/patterns-library#1755]
_--- @danyball Changed that description and ordered the linked issues. See original description below at the comments ------_

The usecase that Marco has is that he does not use any WC from PL. He just wants to use the `materials` package with its exports.

We should revise it with regard to this usecase. We could split a big refactoring in theses smaller parts:

- [x] - `icons and images`: export `.svg` files beside the `.svg.js` #1756 
- [x] - `styles/layout.scss`: use new `variables.scss` for px values. #1757
- [x] - `styles/colors.scss`: remove depricated colors (!and its usages at the WCs!). Remove "Validation" Colorvariables because they differ from the designation of the other variables. https://github.com/axa-ch/patterns-library/issues/1748
- [x] - `typography.scss`: use this new file at `heading` and `text` WC to test the usage (https://github.com/axa-ch/patterns-library/issues/1750). Remove typo logic from old file `typography-and-text.scss`?!

**Comment by danyball** [comment]
A solution for the svg "problem" could be:
```
import {
  ArrowRightSvg
} from '@axa-ch/materials/icons';

<AxaIcon icon={ArrowRightSvg} />
```
See this part of icon docs: "Icon as a SVG string".

**Comment by danyball** [comment]
Some additional infos for that issue:

The usecase that Marco has is that he does not use any WC from PL. He just wants to use the `materials` package with its exports.

We should revise it with regard to this usecase. We could split a big refactoring in theses smaller parts:

- [ ] - `icons and images`: export `.svg` files beside the `.svg.js` #1756 
- [ ] - `styles/layout.scss`: use new `variables.scss` for px values. #1757
- [ ] - `styles/colors.scss`: remove depricated colors (!and its usages at the WCs!). Remove "Validation" Colorvariables because they differ from the designation of the other variables. https://github.com/axa-ch/patterns-library/issues/1748
- [ ] - `typography.scss`: use this new file at `heading` and `text` WC to test the usage (https://github.com/axa-ch/patterns-library/issues/1750). Remove typo logic from old file `typography-and-text.scss`?!

**Comment by danyball** [comment]
Original Issue description from Marko:

>  **As a user in a pod or cra 3+ env, I want to use plug and play the materials module.**
> 
> **I want to use icons as the materials docs say, it's not working (in cra 3+ env)**
> ```
> import {
>   ArrowRightSvg
> } from '@axa-ch/materials/icons';
> ...
> <ArrowRightSvg />
> ```
> won't work even with `@axa-ch/materials/icons/arrow-right.svg.js`
> 
> cra 3+ use svgr, too - like this:
> `import { ReactComponent as AXALogo } from 'images/axa-logo.svg';`
> 
> Thats stuff blocked me. So I copy pasted the images and logo in my project used like above and not using plib. 
> 
> **Typography system (sass not cps):**
> - Whole system was outdated and hard to use. 
> Thats why I wrote a up to date and and plug play version of it in my current project and not using plib again.
> But I already played it back to plib - it's merged in dev, but need to be tested and migrated in all cps.
> 
> - The new version only need one breakpoint variable
> to get the variable I have to import `30-layout.scss`, if I do this then automatically a dependency is imported `@import './breakpoint';` as a user I don't want that imported in my project.
> solution could be to split public variables, mixins, dependencies... .
> 
> 
> 
>

**Comment by danyball** [comment]
We have solved all the child issues. Nice work! Will close this parent now.
