### ISSUE TITLE
[Parent] Storybook Improvements

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1773]
We want to fresh up our Storybook https://patterns.axa.ch/ and show that UX is going hand-in-hand with our technical components. All kinds of customers should consume that Storybook page best.

Thomas created a Figma Scribble to show his "vision":
https://www.figma.com/file/NoDaDyyKkCGueJkJpLNKaC/Storybook?node-id=0%3A1

We cut some sub-task out of that idea to start running with these improvements:

- [x] Update Storybook to the latest version https://github.com/axa-ch/patterns-library/issues/1774
- [ ] Design/create Welcome Page https://github.com/axa-ch/patterns-library/issues/1775
- [x] Create `Latest Releases/Whats new` section with dynamic content https://github.com/axa-ch/patterns-library/issues/1776
- [x] Reorder our components to a flat list https://github.com/axa-ch/patterns-library/issues/1777
- [ ] Create `Development Guide` Page https://github.com/axa-ch/patterns-library/issues/1778
