### ISSUE TITLE
When you click on the nav item, nav should close

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#205]
This happens on Desktop and Side Nav

# Todo

## Mobile

- [x] **Mobile Navigation Links** Click should trigger close
- [x] **Mobile Languages** Click should trigger close
- [x] **Mobile Others** Click should trigger close

## Desktop

- [x] **Submenu** Links click should trigger close

**Comment by AndyOGo** [comment]
@LucaMele 
I think we have two main approaches we could use. Either we code for each component a custom boiler plate script which does the closing logic.

Or we move this responsibility up to a parent component like `header-mobile`, which delegates on class called `js-header-mobile-close`, and any child can just use that.
