### ISSUE TITLE
Date-Picker component

### ISSUE THREAD

**Issue by adrian-hoehn** [axa-ch/patterns-library#244]
For choosing Dates we need a AXA date picker component

**Comment by LucaMele** [comment]
Absolutly. You are free to contribute and implement it. Better to ask first the design team whats their status on it

**Comment by AndyOGo** [comment]
Non-approved design specs can be found here (scroll down manually to **Date Input**):
https://design.axa.com/web-guidelines/Forms-update#forms-elements

**Comment by LucaMele** [comment]
CHAT MIT ANDY:

Luca Mele [10:30 AM]
könntest noch ein paar inputs in die story schreiben
soweit ich denken kann, nur format ist wichtig dass man das konfigureiern kann

Andreas Deuschlinger [10:31 AM]
und locale
er braucht alle übersetztungen für Tage, Monate

Luca Mele [10:32 AM]
stimmt
guter punkt
werde ich hinzufügen

Andreas Deuschlinger [10:32 AM]
und vor allem muss er richtig mit Date Objects umgehen
Schaltjahre usw muss alles funzen
plus ein datepicker besteht aus recht vielen states
vor allem intermediary states
IMHO ich weiss nicht ob das nicht zu hoch für einen Lehrling ist
andererseits muss es ja sowieso lernen
Ich will aufjedenfall nicht, dass der selbe Fehler passiert wie beim letzten Datepicker im alten Styleguide, nach dem motto, das machen wir schon is eh easy
und das Resultat war unbrauchbar, keine Schaltjahre, nicht responsive/mobile-freindly, keine lokalisierung/internationalisierung
:thinking_face: …
und mobile friendly ist eine harte Nuss
das heisst er wird gründlich zwischen touch/mobile interface und klassischen mouse interface unterscheiden müssen
und das click delay usw usf
dafür sollte auch der `tap` event gemerged werden
positionierung des datepicker tooltips ist auch noch wichtig und scroll position im browser
plus keybourd interface sollte auch unterstützt sein
und es müssen unbedingt die Jahre einfach wählbar sein, nicht indem man alle monate durchklicken muss (edited)
ach ich glaub ich schreibs ins issue dazu
hmh, gibt noch kein datepicker issue?

**Comment by AndyOGo** [comment]
# Design

Non-approved design specs can be found here (scroll down manually to **Date Input**):
https://design.axa.com/web-guidelines/Forms-update#forms-elements

**Note:** these will need to be approved for Switzerland.

# Todo

To facilitate a good UX and usability across different browsers and platforms, this UI Element needs to fullfill the following requirements:

## UX

- [ ] It needs to be easy to select valid dates
   - leap years have to work correctly and validate automatically if any factor for regarding leap year changes
- [ ] I shall be easy to select **Day**, **Month** and **Year**
   - Forcing users to click endlessly throughs months to select a specific year is a **NO-GO** 
- [ ] The datepicker should be accessible through following interfaces:
   - classic **Mouse** Interface
   - responsive **Touch/Pointer** Interfaces - including mitigating click delays on mobiles #290 
   - and **Keyboard** Interface

## Technical

- [ ] Use [semantic HTML 5 `<input type="date" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
   - be aware it some formatting limitations, like forcing `yyyy-mm-dd`
- [ ] intermediary state and transitioning events need to be handled properly
   - first the UI will be **entered** by `focussing` it
   - the the state will **move** by various intermediary actions like selecting month or year
   - last the UI will be **leaved** by selecting a specific day or clicking outside of it and thus `blurring` it

## I18n/l10n

- [ ] It has to be **internationalised** and need to be able to handle various formats including their transformation, for:
   - input/output format (used in a data store, api, your name it...)
   - display format (viewed to the user)
- [ ] **localisation** needs to be dynamically changeable:
   - per instance
   - it shall be possible to provide localisation data from outside like `months`, `days` and `date-formats`
   - localisation data for `de-CH`, `enCH`, `fr-CH` and `it-CH` shall be included within the patternslibary
- [ ] only used locales shall be loaded - no big locale chunk
- [ ] standardised [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) shall be used (no moment; attention polyfill will be required)

**Comment by NoahLiechti** [comment]
# Feedback from Ken

- How to select the year easily?
There are two types of datepicker: A normal one, where you can navigate with the arrows and a functional datepicker. The functional datepicker has a dropdown for the month and the year, which makes selecting a specific year very easy.

- How is the mobile solution going to look like?
On a mobile device, the datepicker covers the inputfield up. It’s nearly fullscreen.

- How does the calender open?
The datepicker opens on click in the inputfield, by clicking again on the field the datepicker closes

- Is it possible to enter the date without using the date picker?
Yes, when the date is valid, it gets updated in the datepicker (but you only see it when you reopen the datepicker).

- Should it be possible to change the month dragging the calender to the side?
Maybe for mobile as a hidden feature

**Comment by LucaMele** [comment]
done as MVP. We have a following issues (#561 and #589) so i close this one

**Comment by AndyOGo** [comment]
@LucaMele 
May I ask to reopen this issue and leave it open until all checkpoints of it are tested and confirmed?
