### ISSUE TITLE
Webcomponents randomly not rendered

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#27]
Somehow importing our custom Web Components into Chrome by `HTML Imports` randomly triggers a weird bug in Chrome, which results in rendering the component in one place but **not** in another.

Switching to pure ESnext based `import`'s seems to make Firefox some troubles #25 :
> TypeError: window.customElements is undefined

This bug isn't reasonable and needs to be `1000%` fixed.

# Todo

- [ ] Make `1000%` sure to understand the cause of this bug - no guessing. Ideally easily observable by failing test.
- [ ] order of components lifecycle has to be deterministic
- [ ] Report this bug to Chrome's issue tracker and link it's issue here
- [ ] find reliable cross-browser, testable workaround / bugfix
- [ ] document above solution, and communicate it to everyone involved
- [ ] make sure that every single web component can be reliable rendered in all supported browsers

**Comment by LucaMele** [comment]
Recommendation is to use only Custom Element from the Web-Components.

**Comment by AndyOGo** [comment]
I agree with avoiding HTML imports.

**Comment by AndyOGo** [comment]
It seems that lifecycle execution (`constructor`, `connectedCallback`, `attributeChangedCallback`, `disconnectedCallback`, etc.) of hierarchical/nested components is **NOT** deterministic.

Example:
```html
<axa-parent>
  <axa-child></axa-child>
</axa-parent>
```

**Expected:**
```js
`axa-parent` constructor
`axa-child` constructor
`axa-child` connectedCallback
`axa-parent` connectedCallback
```

**Observed (parent after child):**
```js
`axa-child` constructor
`axa-child` connectedCallback
`axa-parent` constructor
`axa-parent` connectedCallback
```

**Comment by LucaMele** [comment]
Exactly, like proposed specs describe it.

**Comment by LucaMele** [comment]
As HTML imports are not reccomended, we keep this issue as very low prio

**Comment by LucaMele** [comment]
i think is fixed.. feel free to reopen in case is not

**Comment by AndyOGo** [comment]
I don't know if it's fixed 🤔 
Though I haven't seen it a while and we aren't using HTML imports.
