### ISSUE TITLE
Add Webpack for bundling

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#302]
Webpack 4 is out 🎉

# Todo

- [x] One bundle for each component
- [x] Common chunks should be hoisted to `common.js`...
- [ ] Enable sourcemaps for ESnext and SCSS

**Comment by AndyOGo** [comment]
@LucaMele 
Yes, currently I'm sure:
- WebPack + Babel is best suited for the application build of the visual style guide
- and Rollup + Babel is best for the library build provided for our consumers

**Comment by LucaMele** [comment]
ATM there is no need to change a working and simple build. I will close this unless you can provide a clear list of issues with the current build and fixes webpack would bring.

**Comment by LucaMele** [comment]
is used the webpack & rollup aprroach here: https://github.com/axa-ch/axa-ch-core and you are right it is great. I think thought ATM is not real benefit in refactoring it so i close & leave it

**Comment by AndyOGo** [comment]
Our current build is:
- too slow
- modules not bundled correctly, e.g. code splitting
- not very clear

**Comment by LucaMele** [comment]
too slow: What is expected timewise?
modules not bundled correctly: lib export? if so, i disagree as we bundle js not into the components
not very clear: ok needs more docu

**Comment by LucaMele** [comment]
please do not reopen if i close

**Comment by AndyOGo** [comment]
Alright.
Please do not close issues if they are not fixed.

We really need more stuff, also a much better dev experience, including live reloading, etc.

**Comment by LucaMele** [comment]
@AndyOGo there is no issue with the build. If you have personal preferences they dont count. We do tree shaking now, the build has about 150 lines of code, it works as expected and fullfills all requirement. I close issues if they are NOT to be fixed.

**Comment by LucaMele** [comment]
Live reloading is just kids stuff. and if so lets open a issue for each of the desired features and if the owner of the patterns library declines it, it is declined.

**Comment by LucaMele** [comment]
so i create a issue for the documentation and you can create one for whatever u need and we discuss it there. ATM modules are tree shaked and bundled correctly

**Comment by LucaMele** [comment]
We also need to sit together and define how we create issue. Issue with title like: "we need webpack" will not be accepted soon. Issue instead containing a title like: "Build is slow, we need to find out how to improve it" is much better. 

Remember, description should always be written using SMART https://en.wikipedia.org/wiki/SMART_criteria 

A technology is always ONLY a medium for a goal. What we need in the issue description is a goal that needs to be reached or an issue to be fixed

**Comment by AndyOGo** [comment]
@LucaMele 
We really still have no ideal build. We still miss proper code splitting.

> Live reloading is just kids stuff
OMG, live reloading isn't kids stuff. It's a super great feature to increase efficiency and helps allot to deal with cache issues.

> if the owner of the patterns library declines it, it is declined.
I really disagree, is not an comfortable collaboration environment this leaves a totalitarian mark

**Comment by AndyOGo** [comment]
> On the other hand, someone have to stop this useless time consuming conversations.

Alright. You are right, we loose a lot of time cause of issues occurring from communication. This is human, we all have our own ideas, reality, unfortunately miss understandings and so on.

> ATM code is splitted perfectly IMHO. So illuminate me where is the issue.

All our common dependencies still not bundled into `axa-core` for proper reuse.

**Comment by LucaMele** [comment]
@AndyOGo what is the point in creating a issue where only you can understand what is meant? as soon you wont be the only one working on it, i need to describe the issue so that anyone can read it. This is professional development

**Comment by LucaMele** [comment]
"All our common dependencies still not bundled into axa-core for proper reuse": 

Do you mean those in `js` or those in `components`? Also i do not understand the issue yet so please define it clear and open a separate issue (without naming any technology)

**Comment by AndyOGo** [comment]
All our shared dependencies includes `js/` folder, but also reused npm modules like `nanohtml`.

**Comment by AndyOGo** [comment]
> what is the point in creating a issue where only you can understand what is meant?

Okay. What is not clear?

**Comment by LucaMele** [comment]
Which build export do you think of? `lib` or `dist`? on the lib export, is shared and there is no issue, on the dist export is instead not. Which is ok IMHO.

**Comment by LucaMele** [comment]
I was referiing in NOT using something like SMART to define a issue. a issue with a name just like "Add Webpack for bundling" is not clear what is meant.
