### ISSUE TITLE
HTML Attributes VS DOM properties

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#321]
Currently we utilize the attribute DOM APIs which in fact read from markup like `<div data-foo="bar">`.

In contrast the property API read from the generated DOM like `node.property`

# Todo

- [ ] `<axa-foo attr="bar">` creates DOM node from HTML and sets an attribute
- [ ] DOM created through JS
   ```js
   const axaFoo = document.createElement('axa-foo');
   axaFoo.attr = 'bar'; // sets the property of the DOM node (not necessarily the HTML attribute)
   ```
- [ ] Is `attributesChangedCallback` Lifecycle method called?
   - for both - attribute and property changes?
   - for attribute only?
   - for property onyl?

# Resources

- https://developers.google.com/web/fundamentals/web-components/customelements#properties_and_attributes
- https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes
