### ISSUE TITLE
Form elements should stick strictly to HTML 5 Form validation standards

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/patterns-library#588]
## Are you reporting a bug or a feature?

 - [x] Bug
 - [ ] Feature

## Expected Behavior

All our form components should implement the [HTML5 Form Validation Standard](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation).

**Todo:**

- [ ] input type validation for email, phone, sms, date, number, zip-code, etc
- [ ] error message display (incl. i18n)
- [ ] `required` field
- [ ] `pattern` regex validations
- [ ] `placeholder`s
- [ ] field sanitization
- [ ] and more...

https://www.the-art-of-web.com/html/html5-form-validation/ 

## Actual Behavior

Currently we have `error` attributes used as `boolean` flags, instead of using `valid`/`invalid` boolean flags and `error` for error messages or objects.

**Comment by LucaMele** [comment]
Closing as V2 is released. If issue is still relevant in v2, please re-open

**Comment by AndyOGo** [comment]
@LucaMele is this done?

**Comment by LucaMele** [comment]
Will be done differently, issue not relevant
